### ISSUE TITLE
Slow Queries -> DB need optimizations

### ISSUE THREAD

**Issue by olb1ue** [dewi-alliance/helium-etl-lite#17]
Once the etl runs for a few weeks, the rewards table is getting really slow with queries that are super fast on DeWi ETL. Need to troubleshoot what is causing this and implement optimizations that will fix.

**Comment by jamiew** [comment]
How are you queries and indexes looking? Usual suspect. But also note that the DeWi ETL machine is pretty beefy

**Comment by olb1ue** [comment]
The queries that seem to be running slow (3+ minutes) are when there aren't any results for example:

`select * from rewards where block > 995071 and gateway = '11ee44qxTN5SsQrwAYBssz9Q2nETJckVUq3kdn3EvNaVgJoPwJb';`

As for indexes, I have the block field as an index: `create index on rewards (block);`
Maybe it would help to do a index for account and gateway like the full ETL does? 
The only other thing I think is that full ETL does `primary key(block, account, gateway)` which this ETL can't do currently since there are duplicate primary key issues.

**Comment by olb1ue** [comment]
Adding and index to 'gateway' did the trick! Thanks @jamiew
