### ISSUE TITLE
individual rewards

### ISSUE THREAD

**Issue by 70hnKuky** [dewi-alliance/helium-etl-lite#19]
Not shure if i understand this correctly. 

"Because of the way blockchain-node stores rewards info, the first ~300 blocks after the snapshot height won't incldue gateway or type information for specific rewards. All rewards with type = 'rewards_v2' are the total rewards paid to that account vs individual rewards that you will see being loaded into the rewards db after the first ~300 blocks after the snapshot height of the node."

After ~300 blocks it shuld start filling individual rewards in table rewards with gateway address included?  
Beacause after 5000 blocks i still cant see it.

**Comment by 70hnKuky** [comment]
Ok i have fixed it with help from madninjas discord post: https://discord.com/channels/404106811252408320/730245219974381708/913079394673778698

"look in your sys.config for {store_json, false}, and change false to true"

**Comment by olb1ue** [comment]
thanks for bringing this up. that is a new option for node that previously defaulted to true so instructions will need to be updated. We should probably not even be loading rewards if they have type = 'rewards_v2' since it is a totally different schema than what we want.

**Comment by 70hnKuky** [comment]
You are welcome. great project by the way. 👍
can't wait for filters.
